# Generated by Django 5.0.6 on 2024-06-26 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productspecifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن نظر')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت محصول',
                'verbose_name_plural': 'کامنت های محصول',
            },
        ),
    ]
